export const PARTNER_KEY_UPDATED = 'PARTNER_KEY_UPDATED';
export const DETAILS_UPDATED = 'DETAILS_UPDATED';
export const POST_DETAILS_FIRST_SUCCESS = 'POST_DETAILS_FIRST_SUCCESS';
export const POST_DETAILS_FIRST_REQUEST = 'POST_DETAILS_FIRST_REQUEST';
export const POST_DETAILS_FIRST_FAILURE = 'POST_DETAILS_FIRST_FAILURE';
export const E_COMERCE_SUPORTED_UPDATED = 'E_COMERCE_SUPORTED_UPDATED';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';

export const GET_LOGOUT = 'GET_LOGOUT';

export const GET_SHOPIFY_INSTALL_LINK_REQUEST = 'GET_SHOPIFY_INSTALL_LINK_REQUEST';
export const GET_SHOPIFY_INSTALL_LINK_ERROR = 'GET_SHOPIFY_INSTALL_LINK_ERROR';
export const GET_SHOPIFY_INSTALL_LINK_SUCCESS = 'GET_SHOPIFY_INSTALL_LINK_SUCCESS';

export const GET_SHOPIFY_CALLBACK_REQUEST = 'GET_SHOPIFY_CALLBACK_REQUEST';
export const GET_SHOPIFY_CALLBACK_ERROR = 'GET_SHOPIFY_CALLBACK_ERROR';
export const GET_SHOPIFY_CALLBACK_SUCCESS = 'GET_SHOPIFY_CALLBACK_SUCCESS';

export const GET_VERIFY_EMAIL_REQUEST = 'GET_VERIFY_EMAIL_REQUEST';
export const GET_VERIFY_EMAIL_ERROR = 'GET_VERIFY_EMAIL_ERROR';
export const GET_VERIFY_EMAIL_SUCCESS = 'GET_VERIFY_EMAIL_SUCCESS';