export const GET_AMAZON_PAY_DETAILS_REQUEST = 'GET_AMAZON_PAY_DETAILS_REQUEST';
export const GET_AMAZON_PAY_DETAILS_ERROR = 'GET_AMAZON_PAY_DETAILS_ERROR';
export const GET_AMAZON_PAY_DETAILS_SUCCESS = 'GET_AMAZON_PAY_DETAILS_SUCCESS';
export const CANCEL_AMAZON_PAY_DETAILS_REQUEST = 'CANCEL_AMAZON_PAY_DETAILS_REQUEST';

export const GET_GENERAL_SETTINGS_REQUEST = 'GET_GENERAL_SETTINGS_REQUEST';
export const GET_GENERAL_SETTINGS_ERROR = 'GET_GENERAL_SETTINGS_ERROR';
export const GET_GENERAL_SETTINGS_SUCCESS = 'GET_GENERAL_SETTINGS_SUCCESS';
export const CANCEL_GENERAL_SETTINGS_REQUEST = 'CANCEL_GENERAL_SETTINGS_REQUEST';

export const GET_AMAZON_MODAL_ORDER_REQUEST = 'GET_AMAZON_MODAL_ORDER_REQUEST';
export const GET_AMAZON_MODAL_ORDER_ERROR = 'GET_AMAZON_MODAL_ORDER_ERROR';
export const GET_AMAZON_MODAL_ORDER_SUCCESS = 'GET_AMAZON_MODAL_ORDER_SUCCESS';

export const GET_HOME_SCREEN_REQUEST = 'GET_HOME_SCREEN_REQUEST';
export const GET_HOME_SCREEN_SUCCESS = 'GET_HOME_SCREEN_SUCCESS';
export const GET_HOME_SCREEN_ERROR = 'GET_HOME_SCREEN_ERROR';
export const CANCEL_HOME_SCREEN_REQUEST = 'CANCEL_HOME_SCREEN_REQUEST';

export const GET_VOICES_REQUEST = 'GET_VOICES_REQUEST';
export const GET_VOICES_SUCCESS = 'GET_VOICES_SUCCESS';
export const GET_VOICES_ERROR = 'GET_VOICES_ERROR';
export const CANCEL_VOICES_REQUEST = 'CANCEL_VOICES_REQUEST';
export const POST_VOICES_REQUEST = 'POST_VOICES_REQUEST';
export const CANCEL_POST_VOICES_REQUEST = 'CANCEL_POST_VOICES_REQUEST';

export const GET_BASIC_DIALOGUE_MESSAGES_REQUEST = 'GET_BASIC_DIALOGUE_MESSAGES_REQUEST';
export const GET_BASIC_DIALOGUE_MESSAGES_ERROR = 'GET_BASIC_DIALOGUE_MESSAGES_ERROR';
export const GET_BASIC_DIALOGUE_MESSAGES_SUCCESS = 'GET_BASIC_DIALOGUE_MESSAGES_SUCCESS';
export const CANCEL_BASIC_DIALOGUE_MESSAGES_REQUEST = 'CANCEL_BASIC_DIALOGUE_MESSAGES_REQUEST';

export const GET_CONVERSATION_TOOLS_SUCCESS = 'GET_CONVERSATION_TOOLS_SUCCESS';
export const GET_CONVERSATION_TOOLS_REQUEST = 'GET_CONVERSATION_TOOLS_REQUEST';
export const GET_CONVERSATION_TOOLS_ERROR = 'GET_CONVERSATION_TOOLS_ERROR';
export const CANCEL_CONVERSATION_TOOLS_REQUEST = 'CANCEL_GET_CONVERSATION_TOOLS_REQUEST';
export const POST_TOGGLE_CONVERSATION_TOOLS = 'POST_TOGGLE_CONVERSATION_TOOLS';
export const UPDATE_CURRENT_TOOL = 'UPDATE_CURRENT_TOOL';

export const GET_EDIT_TOOL_SUCCESS = 'GET_EDIT_TOOL_SUCCESS';
export const GET_EDIT_TOOL_REQUEST = 'GET_EDIT_TOOL_REQUEST';
export const GET_EDIT_TOOL_ERROR = 'GET_EDIT_TOOL_ERROR';
export const CANCEL_GET_EDIT_TOOL_REQUEST = 'CANCEL_GET_EDIT_TOOL_REQUEST';
export const POST_EDIT_TOOL_TOOLS = 'POST_EDIT_TOOL_TOOLS';

export const POST_AMAZON_PAY_DETAILS_REQUEST = 'POST_AMAZON_PAY_DETAILS_REQUEST';
export const POST_AMAZON_PAY_DETAILS_ERROR = 'POST_AMAZON_PAY_DETAILS_ERROR';
export const POST_AMAZON_PAY_DETAILS_SUCCESS = 'POST_AMAZON_PAY_DETAILS_SUCCESS';

export const POST_GENERAL_SETTINGS_REQUEST = 'POST_GENERAL_SETTINGS_REQUEST';
export const POST_GENERAL_SETTINGS_ERROR = 'POST_GENERAL_SETTINGS_ERROR';
export const POST_GENERAL_SETTINGS_SUCCESS = 'POST_GENERAL_SETTINGS_SUCCESS';
export const CLEAR_GENERALSETTINGS = 'CLEAR_GENERALSETTINGS';

export const POST_UPDATE_MESSAGE_REQUEST = 'POST_UPDATE_MESSAGE_REQUEST';
export const POST_UPDATE_MESSAGE_ERROR = 'POST_UPDATE_MESSAGE_ERROR';
export const POST_UPDATE_MESSAGE_SUCCESS = 'POST_UPDATE_MESSAGE_SUCCESS';

export const POST_GENERAL_UPLOAD_LOGO_REQUEST = 'POST_GENERAL_UPLOAD_LOGO_REQUEST';
export const POST_GENERAL_UPLOAD_LOGO_ERROR = 'POST_GENERAL_UPLOAD_LOGO_ERROR';
export const POST_GENERAL_UPLOAD_LOGO_SUCCESS = 'POST_GENERAL_UPLOAD_LOGO_SUCCESS';
export const CANCEL_POST_GENERAL_UPLOAD_LOGO_REQUEST = 'CANCEL_POST_GENERAL_UPLOAD_LOGO_REQUEST';

export const VOICE_PLAY = 'VOICE_PLAY';
export const VOICE_STOP = 'VOICE_STOP';

export const USER_MENU_TOGGLE = 'USER_MENU_TOGGLE';
export const ASIDE_MENU_TOGGLE = 'ASIDE_MENU_TOGGLE';
export const DROP_USER_MENU_TOGGLE = 'DROP_USER_MENU_TOGGLE';
export const TOOL_MENU_TOGGLE = 'TOOL_MENU_TOGGLE';
export const MENU_CLOSE = 'MENU_CLOSE';
